workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.myApp"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          # Update iOS deployment target to 13.0
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/platform :ios, '\''12.0'\''/platform :ios, '\''13.0'\''/g' Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET'\''\] = '\''12.0'\''/IPHONEOS_DEPLOYMENT_TARGET'\''\] = '\''13.0'\''/g' Podfile
          pod install
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --no-codesign
      - name: Verify build output
        script: |
          echo "Build completed successfully!"
          ls -la build/ios/iphoneos/
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - void7775@gmail.com
      scripts:
        - name: Upload to Codemagic Artifacts
          script: |
            echo "iOS build artifacts uploaded successfully!"
