name: Debug iOS Environment

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: System Info
      run: |
        echo "=== SYSTEM INFO ==="
        uname -a
        sw_vers
        echo "=== XCODE INFO ==="
        xcode-select --print-path
        xcodebuild -version
        echo "=== AVAILABLE SIMULATORS ==="
        xcrun simctl list devices available
        
    - name: Setup Flutter (minimal)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        
    - name: Flutter Environment
      run: |
        echo "=== FLUTTER INFO ==="
        which flutter
        flutter --version
        flutter doctor -v
        
    - name: Create New Flutter App
      run: |
        echo "=== CREATING NEW FLUTTER APP ==="
        flutter create test_app --platforms=ios
        cd test_app
        flutter build ios --debug --no-codesign
        
    - name: Check Build Success
      run: |
        echo "=== BUILD OUTPUT ==="
        ls -la test_app/build/ios/
        echo "If we see this message, the basic Flutter iOS build works!"
