name: Quick iOS Test

on:
  workflow_dispatch:

jobs:
  quick_test:
    runs-on: macos-latest
    timeout-minutes: 10  # Short timeout to prevent hanging
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      timeout-minutes: 2
      
    - name: System Check
      timeout-minutes: 1
      run: |
        echo "macOS Version:"
        sw_vers
        echo "Xcode Version:"
        xcodebuild -version
      
    - name: Setup Flutter (Quick)
      uses: subosito/flutter-action@v2
      timeout-minutes: 3
      with:
        flutter-version: '3.22.0'
        cache: true
        
    - name: Flutter Doctor
      timeout-minutes: 2
      run: flutter doctor
      
    - name: Create Test App
      timeout-minutes: 2
      run: |
        flutter create test_ios_app --platforms=ios
        
    - name: Quick Build Test
      timeout-minutes: 5
      run: |
        cd test_ios_app
        flutter build ios --debug --no-codesign
        echo "SUCCESS: Basic iOS build completed!"
        
    - name: Final Status
      run: echo "✅ Test completed successfully!"
