name: Simple iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios_build:
    runs-on: macos-13  # Use specific macOS version for stability
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Clean previous builds
      run: flutter clean
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Update iOS deployment target
      run: |
        # Ensure iOS deployment target is set correctly
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' ios/Runner.xcodeproj/project.pbxproj
        
    - name: Build iOS (Debug first - faster)
      run: |
        flutter build ios --debug --no-codesign
        
    - name: Build iOS (Release)
      run: |
        flutter build ios --release --no-codesign
        
    - name: List build output
      run: |
        ls -la build/ios/
        ls -la build/ios/iphoneos/ || echo "iphoneos folder not found"
        
    - name: Upload iOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-${{ github.run_number }}
        path: |
          build/ios/iphoneos/Runner.app
          build/ios/Debug-iphoneos/Runner.app
        retention-days: 7
